[info]
name = "sfml-proj"
version = "0.1.0"
title = "sfml project"
author = "me"
factorio_version = "2.0"
dependencies = ["base >= 2.0"]
description = "A basic sfml project."
[compile]
outDir = "/dist"
